/* AUTO-GENERATED by tools/generate_flag_remap.py - DO NOT EDIT BY HAND.
 * USA-baseline local-flag ordinal remap, matched strictly by semantic name.
 * Retail enums are preprocessed without PC_PORT so regional branches remain
 * visible. A remap byte is usable only when the matching Valid byte is 1;
 * baseline-only names, END markers, and out-of-enum ordinals are invalid.
 *
 * EU (runtime-supported):
 *   LocalFlags1: semantic-remaps=238; baseline-only=[KS_A06=249, KS_B18=250, KS_C21=251, KS_C25=252]; target-only=[HIKYOU_00_T0=11, HIKYOU_00_H00=33, SOUGEN_07_H00=145]
 *   LocalFlags2: semantic-remaps=0; baseline-only=[SHOP00_BOMBBAG=205, CAFE_01_CAP_1=206, KS_A02=207, KS_A09=208, KS_A18=209, KS_B07=210, KS_B16=211]; target-only=[]
 *   LocalFlags3: semantic-remaps=0; baseline-only=[MACHI_CHIKA2_10_CAP_0=199, KS_C02=200]; target-only=[]
 *   LocalFlags4: semantic-remaps=0; baseline-only=[KS_B06=135, KS_B15=136, KS_B01=137, KS_B12=138, KS_C12=139, KS_C37=140]; target-only=[]
 *   LocalFlags5: semantic-remaps=0; baseline-only=[LV1_12_CAP_0=86]; target-only=[]
 *   identical: Flag, LocalFlags6, LocalFlags7, LocalFlags8, LocalFlags9, LocalFlags10, LocalFlags11, LocalFlags12
 * JP (source-only; runtime unverified):
 *   LocalFlags1: semantic-remaps=238; baseline-only=[KS_A06=249, KS_B18=250, KS_C21=251, KS_C25=252]; target-only=[HIKYOU_00_T0=11, HIKYOU_00_H00=33, SOUGEN_07_H00=145]
 *   LocalFlags2: semantic-remaps=0; baseline-only=[KS_A02=207, KS_A09=208, KS_A18=209, KS_B07=210, KS_B16=211]; target-only=[]
 *   LocalFlags3: semantic-remaps=0; baseline-only=[KS_C02=200]; target-only=[]
 *   LocalFlags4: semantic-remaps=0; baseline-only=[KS_B06=135, KS_B15=136, KS_B01=137, KS_B12=138, KS_C12=139, KS_C37=140]; target-only=[]
 *   LocalFlags5: semantic-remaps=0; baseline-only=[LV1_12_CAP_0=86]; target-only=[]
 *   identical: Flag, LocalFlags6, LocalFlags7, LocalFlags8, LocalFlags9, LocalFlags10, LocalFlags11, LocalFlags12
 */
#ifndef FLAG_REMAP_GENERATED_H
#define FLAG_REMAP_GENERATED_H

#define FLAG_REMAP_BANK_COUNT 12
#define FLAG_REMAP_TABLE_WIDTH 256

#ifdef __cplusplus
extern "C" {
#endif

/* [bankNumber-1][USA baseline ordinal] -> active-region ordinal. */
extern const unsigned char gFlagRemapEU[FLAG_REMAP_BANK_COUNT][FLAG_REMAP_TABLE_WIDTH];
extern const unsigned char gFlagRemapJP[FLAG_REMAP_BANK_COUNT][FLAG_REMAP_TABLE_WIDTH];

/* 1 only for BEGIN or a semantic USA name present in the target region. */
extern const unsigned char gFlagRemapEUValid[FLAG_REMAP_BANK_COUNT][FLAG_REMAP_TABLE_WIDTH];
extern const unsigned char gFlagRemapJPValid[FLAG_REMAP_BANK_COUNT][FLAG_REMAP_TABLE_WIDTH];

#ifdef __cplusplus
}
#endif

#endif /* FLAG_REMAP_GENERATED_H */
